all: lib componentes

componentes: window spawn 

lib:
	@gcc -o funcoes.o -c funcoes.c

window:
	@gcc -o window.o -c window.c

spawn:
	@gcc -o spawn.o -c spawn.c

const:
	@gcc -o const.o -c const.c

filter:
	@gcc -o filter.o -c filter.c
