all: controlador cont_node run_controlador

run_controlador:
	@echo "#########"
	@echo "# 2.1.1 #"
	@echo "#########"
	@./controlador < input

controlador:
	@gcc controlador.c -o controlador

cont_node:
	@gcc node.c -o node
